#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

require_root

REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
NGINX_AVAILABLE_DIR="${NGINX_AVAILABLE_DIR:-/etc/nginx/sites-available/home-server}"
NGINX_ENABLED_FILE="${NGINX_ENABLED_FILE:-/etc/nginx/sites-enabled/home-server.conf}"
TMP_ROOT="$(mktemp -d)"
STAGED_OUTPUT_DIR="${TMP_ROOT}/nginx-generated"
STAGED_AVAILABLE_DIR="${TMP_ROOT}/available"
STAGED_ENABLED_FILE="${TMP_ROOT}/home-server.conf"
BACKUP_ROOT="$(mktemp -d)"
BACKUP_AVAILABLE_DIR="${BACKUP_ROOT}/available"
BACKUP_ENABLED_FILE="${BACKUP_ROOT}/home-server.conf"

cleanup() {
  rm -rf "${TMP_ROOT}" "${BACKUP_ROOT}"
}

restore_previous_config() {
  log "Restoring previous managed Nginx config..."
  mkdir -p "${NGINX_AVAILABLE_DIR}"
  find "${NGINX_AVAILABLE_DIR}" -type f -name '*.conf' -delete

  if [[ -d "${BACKUP_AVAILABLE_DIR}" ]]; then
    shopt -s nullglob
    local backup_files=("${BACKUP_AVAILABLE_DIR}"/*.conf)
    shopt -u nullglob

    if [[ "${#backup_files[@]}" -gt 0 ]]; then
      cp "${backup_files[@]}" "${NGINX_AVAILABLE_DIR}/"
    fi
  fi

  if [[ -f "${BACKUP_ENABLED_FILE}" ]]; then
    install -m 0644 "${BACKUP_ENABLED_FILE}" "${NGINX_ENABLED_FILE}"
  else
    rm -f "${NGINX_ENABLED_FILE}"
  fi
}

trap cleanup EXIT

log "Rendering Nginx config..."
cd "${REPO_ROOT}"
NGINX_OUTPUT_DIR="${STAGED_OUTPUT_DIR}" node scripts/render-nginx-config.mjs

shopt -s nullglob
rendered_files=("${STAGED_OUTPUT_DIR}"/*.conf)
shopt -u nullglob

if [[ "${#rendered_files[@]}" -eq 0 ]]; then
  fail "No enabled site configs were rendered. Refusing to replace the live Nginx config with an empty managed config."
fi

log "Building staged managed config..."
mkdir -p "${STAGED_AVAILABLE_DIR}"
cp "${rendered_files[@]}" "${STAGED_AVAILABLE_DIR}/"
{
  echo '# Generated by home-server/scripts/install-nginx-config.sh'
  echo '# Do not edit directly.'
  for file in "${STAGED_AVAILABLE_DIR}"/*.conf; do
    echo
    echo "# include: ${file}"
    cat "${file}"
  done
} > "${STAGED_ENABLED_FILE}"

log "Backing up current managed config..."
mkdir -p "${NGINX_AVAILABLE_DIR}"
mkdir -p "$(dirname "${NGINX_ENABLED_FILE}")"

if compgen -G "${NGINX_AVAILABLE_DIR}/*.conf" > /dev/null; then
  mkdir -p "${BACKUP_AVAILABLE_DIR}"
  cp "${NGINX_AVAILABLE_DIR}"/*.conf "${BACKUP_AVAILABLE_DIR}/"
fi

if [[ -f "${NGINX_ENABLED_FILE}" ]]; then
  install -m 0644 "${NGINX_ENABLED_FILE}" "${BACKUP_ENABLED_FILE}"
fi

log "Installing staged config to ${NGINX_AVAILABLE_DIR}..."
find "${NGINX_AVAILABLE_DIR}" -type f -name '*.conf' -delete
cp "${STAGED_AVAILABLE_DIR}"/*.conf "${NGINX_AVAILABLE_DIR}/"
install -m 0644 "${STAGED_ENABLED_FILE}" "${NGINX_ENABLED_FILE}"

log "Testing and reloading Nginx..."
if ! nginx -t; then
  restore_previous_config
  fail "Nginx config test failed. Previous managed config has been restored."
fi

systemctl reload nginx
log "Nginx config installed."
