#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

require_root

REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
NGINX_OUTPUT_DIR="${NGINX_OUTPUT_DIR:-${REPO_ROOT}/nginx/generated}"
NGINX_AVAILABLE_DIR="${NGINX_AVAILABLE_DIR:-/etc/nginx/sites-available/home-server}"
NGINX_ENABLED_FILE="${NGINX_ENABLED_FILE:-/etc/nginx/sites-enabled/home-server.conf}"

log "Rendering Nginx config..."
cd "${REPO_ROOT}"
node scripts/render-nginx-config.mjs

log "Installing generated config to ${NGINX_AVAILABLE_DIR}..."
mkdir -p "${NGINX_AVAILABLE_DIR}"
find "${NGINX_AVAILABLE_DIR}" -type f -name '*.conf' -delete
cp "${NGINX_OUTPUT_DIR}"/*.conf "${NGINX_AVAILABLE_DIR}/"

log "Building aggregate enabled config ${NGINX_ENABLED_FILE}..."
{
  echo '# Generated by home-server/scripts/install-nginx-config.sh'
  echo '# Do not edit directly.'
  for file in "${NGINX_AVAILABLE_DIR}"/*.conf; do
    echo
    echo "# include: ${file}"
    cat "${file}"
  done
} > "${NGINX_ENABLED_FILE}"

log "Testing and reloading Nginx..."
nginx -t
systemctl reload nginx
log "Nginx config installed."
